name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      python-version: 3.7

    steps:
      - name: Check out git
        uses: actions/checkout@v2

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install requirements
        run: python -m pip install -r requirements.txt --use-feature=2020-resolver

       TODO
      - name: Run Unit Test
        run: python -m unittest discover unit-tests
