name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
      - name: Check out git
        uses: actions/checkout@v2

      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install new pip version
        uses: python.exe -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      #- name: Run Unit Test
      #  run: python -m unittest discover tests
